[book]
authors = []
language = "de"
multilingual = false
src = "src"

[output.html]
additional-css = ["css/inforz.css"]
git-repository-url = "https://github.com/d120/cyberinforz"

[output.html.fold]
enable = true
