[book]
authors = []
language = "de"
multilingual = false
src = "src"
title = "Inforz zur Winterophase 2020"

[output.html]
additional-css = ["css/inforz.css"]
git-repository-url = "https://github.com/d120/cyberinforz"

[output.html.fold]
enable = true
